-- FISH_INFO 테이블에서 잡은 BASS와 SNAPPER의 수를 출력하는 SQL 문을 작성해주세요.

-- 컬럼명은 'FISH_COUNT`로 해주세요.

-- SELECT COUNT(*) as FISH_COUNT
-- FROM FISH_INFO fi
-- LEFT JOIN FISH_NAME_INFO fni ON fi.FISH_TYPE = fni.FISH_TYPE
-- WHERE fni.FISH_NAME = 'BASS' or fni.FISH_NAME = 'SNAPPER';
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE FISH_TYPE IN (
    SELECT FISH_TYPE
    FROM FISH_NAME_INFO
    WHERE FISH_NAME IN ('BASS', 'SNAPPER')
);